spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-microservice
          uri: lb://user-service
          predicates:
            - Path=/todo/user/**
        - id: todo-microservice
          uri: lb://todo-service
          predicates:
            - Path=/todo/items/**


server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    instance:
      hostname: localhost
      leaseRenewalIntervalInSeconds: 240