spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/todo/user/**
          filters:
            - AuthenticationFilter

        - id: todo-service
          uri: lb://todo-service
          predicates:
            - Path=/todo/items/**
          filters:
            - AuthenticationFilter

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/todo/auth/**


server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    instance:
      hostname: localhost
      leaseRenewalIntervalInSeconds: 240