server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice-todo-app
    username: postgres
    password: Jenkins@2020
    show-sql: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      .ddl-auto: update
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    instance:
      hostname: localhost
      leaseRenewalIntervalInSeconds: 240