server:
  port: 8081

spring:
  application:
    name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    instance:
      hostname: localhost
      leaseRenewalIntervalInSeconds: 240